---
version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
